# Azure Pipelines configuration for Firely Server Documentation
# This pipeline builds the documentation using Sphinx and fails if there are any warnings or errors

trigger:
  branches:
    include:
    - main
    - develop
    # - feature/*

pr:
  branches:
    include:
    - main
    - develop

resources:
  repositories:
  - repository: templates
    type: github
    name: FirelyTeam/azure-pipeline-templates
    endpoint: FirelyTeam
    ref: refs/tags/v1

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildDocumentation
  displayName: 'Build Documentation'
  jobs:
  - template: buildDocumentation.yml@templates
    parameters:
      pythonVersion: '3.9'